 # training params (model, hyperparams)

global:
  random_state: 42
  n_splits: 3
  primary_metric: 'recall'

model:
  - name: logistic_regression
    params:
      solver: ['saga']
      penalty: [l1,l2]
      max_iter: [100]
      C: [0.1]
    store_path: artifacts

  # - name: RandomForestClassifier
  #   params:
  #     n_estimators: 50
  #     max_depth: 10
  #     random_state: 42
  #   store_path: artifacts

metric:
  - 'recall'
  - 'accuracy'
  - 'roc-auc'

output:
  model: 'artifacts/models'
  metrics: 'artifacts/metrics'
